debug: false
spring:
  datasource:
    url: jdbc:mysql://my-db:3306/webflash?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: webflash
    password: webflash190602@ABC
  jpa:
    hibernate:
      ddl-auto: update
  activiti:
    #    配置为true的时候自动检查resources/bpmn/目录下的工作流定义文件并部署到数据库表中
    check-process-definitions: true
    #    启动的时候配置为true初始化工作流相关表
    database-schema-update: true
    history-level: full
    db-history-used: true
    process-definition-location-prefix: classpath:/bpmn/
server:
  tomcat:
    basedir: /data/app/web-flash/runtime/tmp
